### ISSUE TITLE
ocpp code missing

### ISSUE THREAD

**Issue by emilhe** [OrangeTux/pygrunn-ocpp#1]
Could you add the ocpp code somewhere? The ocpp package on pypi is empty so far, but i would like to know how it works.

**Comment by OrangeTux** [comment]
@emilhe This weekend I pubished the OCPP framework that this project uses. You can find it here: https://github.com/mobilityhouse/ocpp

*Note*: the Pypi build is currently broken: a PR is already up and tomorrow it will be fixed.

**Comment by emilhe** [comment]
That looks great, thanks!
